### ISSUE TITLE
Minor doc detail GTCMD

### ISSUE THREAD

**Issue by vandys** [hperaza/RSX280#7]
In sysfunc.hlp, .GTCMD says the first _word_ of the buffer has the count.  In fact, it's the first _byte_?

**Comment by hperaza** [comment]
Yes, indeed! Note that both sysfunc.hlp and syslib.hlp help files are rather outdated at this point, so the information they contain is no longer accurate. I'm in process of writing a couple of documents detailing the system calls, syslib and fcslib routines, I hope to upload the first version in about a week or so. Then, I'm planning to document MCR, ICP and other utilities... lots of work!

**Comment by hperaza** [comment]
Just added a PDF file documenting the system calls to the Docs directory.
